import Head from 'next/head'
import Header from '@components/Header'
import Image from 'next/image'
import Paragraph from '@components/Paragraph'
import ClickableTile from '@components/ClickableTile'
import Tile from '@components/Tile'
import styles from '@styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TeaEngine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>

      <main className={styles.main}>
        <Header title="TeaEngine" />

        <Paragraph text="Tea engine is a game engine being wrote in nelua with a custom system that should give better performance, it is focused on ease of use for the user without creating a cluttered a user interface."></Paragraph>

        <div className={styles.gridlist}>
          <Tile title="Modular" text="Allows only the things you require to be a part of your build"></Tile>
          <Tile title="Simple" text="Simple use for the end user, allowing them to worry less about the engine and more about what they are doing"></Tile>
          <Tile title="Smaller scope" text="The project has a smaller scope than game engines as Unity, this means you won't get distracted by the amount of tools, leading to faster and more productive. If there are too many tools you may get distracted by them or they may even get in your way"></Tile>
          <Tile title="Focused" text="The game engine is focused on what you need to make a game, if you don't need it, and it doesn't have a good, well thought out purpose it is not there"></Tile>
        </div>

        <Header title="Links"></Header>

        <ClickableTile title="The GitHub page" text="Click here to be taken to the actual GitHub Page" link="https://github.com/TeaSpillStudios/TeaEngine"></ClickableTile>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
