import Head from 'next/head'
import Header from '@components/Header'
import Image from 'next/image'
import Paragraph from '@components/Paragraph'
import ClickableTile from '@components/ClickableTile'
import Tile from '@components/Tile'
import styles from '@styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TeaFS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>

      <main className={styles.main}>
        <Header title="TeaFS" />

        <Paragraph text="TeaFS is a C library wrote for TeaEngine to manipulate the filesystem."></Paragraph>

        <div className={styles.gridlist}>
          <Tile title="Quick and simple" text="TeaFS only does exactly what it needs to and is extremely easy to use, you simply include it in a C file and call any of the basic functions that are provided."></Tile>
        </div>

        <Header title="Links"></Header>

        <ClickableTile title="The GitHub page" text="Click here to be taken to the actual GitHub Page" link="https://github.com/TeaSpillStudios/TeaFS"></ClickableTile>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
